
name: CI

# Define os triggers que vão disparar o Action
on: 
  push: 
    branches: [main]
  # pull_request:
  #  branches: [main]

  # Habilita o disparo manual pelo Actions tab
  workflow_dispatch:

jobs:
  # Esse workflow possui um unico job chamado "CI"
  CI:

    runs-on: ubuntu-lastest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup do NodeJS
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.3.2
      - name: Instalação do Mocha e pacote de dependencia para teste
        run: |
          cs src;
          npm install -g mocha;
          npm install
